- hosts: test-server
  become: yes
  tasks: 
   - name: install docker
     apt: 
       pkg: docker.io
       state: present
   - name: start docker service
     service:
       name: docker
       state: started
       enabled: true
   - name: deploy addressbook application
     command: docker run -itd --name monu -p 8090:8080 somya1196/addressbook:8.2
